apiVersion: v1
kind: Service
metadata:
  labels:
    name: docktor
  name: docktor
spec:
  selector:
    app: docktor
  ports:
    - port: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docktor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docktor
  template:
    metadata:
      name: docktor
      labels:
        app: docktor
    spec:
      containers:
      - name: docktor
        image: chriskirkland/docktor:latest
        command: ["tail", "-f", "/var/log/dmesg"]
---
