# A mock daemonset to serve as a scrape target for Prometheus
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-random-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prom-random-deploy
  template:
    metadata:
      name: prom-random-deploy
      labels:
        app: prom-random-deploy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: prom-random
        image: chriskirkland/prom-random:latest
        resources:
          requests:
            memory: "20Mi"
          limit:
            memory: "50Mi"
        ports:
        - name: web
          containerPort: 8080
